version: '3.7'
services:
  web:
    build:
      context: .
      target: builder
    command: go run main.go
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=development_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
